<?php

return [
    'min_completed_campaigns' => max(1, (int) env('STOREFRONT_MIN_COMPLETED_CAMPAIGNS', 3)),
    'prohibited_keywords' => [
        'tigrinho',
        'tigrinhos',
        'fortune tiger',
        'fortunetiger',
        'jogo do tigre',
        'jogodotigre',
        'fortune ox',
        'fortuneox',
        'touro da fortuna',
        'fortune rabbit',
        'fortunerabbit',
        'coelho da fortuna',
        'fortune dragon',
        'fortunedragon',
        'fortune mouse',
        'fortunemouse',
        'fortune snake',
        'fortunesnake',
        'pgsoft',
        'pg soft',
        'jogo do bicho',
        'jogodobicho',
        'bichao',
        'sweet bonanza',
        'gates of olympus',
        'aviator crash',
        'jogo de azar',
        'jogos de azar',
        'caca niquel',
        'cacaniquel',
        'slot machine',
        'slots casino',
        'cassino online',
        'casino online',
        'cassinoonline',
        'casinoonline',
        'roleta online',
        'blaze.com',
        'blaze.bet',
    ],
];
